spring:
  application:
    name: microservicio-zuul
server:
  port: 8090
eureka:
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    alumnos:
      path: /api/alumnos/**
      serviceId: microservicio-alumnos

