spring:
  application:
    name: microservicio-alumnos
  h2:
    console:
      settings:
        trace: false
        web-allow-others: false
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: create
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          type: trace
server:
  port: ${PORT:0}
eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
